services:
  - type: web
    name: flow-downloader
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 24
